#!/usr/bin/env python3
"""compliance-report.json → PDF (fpdf2)."""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def pdf_safe(text: str) -> str:
    """Helvetica latin-1 için metin dönüşümü."""
    text = (
        text.replace("—", "-")
        .replace("–", "-")
        .replace(""", '"')
        .replace(""", '"')
        .replace("'", "'")
        .replace("'", "'")
        .replace("≥", ">=")
    )
    tr = str.maketrans(
        "ıİğĞüÜşŞöÖçÇ",
        "iIgGuUsSoOcC",
    )
    return text.translate(tr).encode("latin-1", "replace").decode("latin-1")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-i", "--input", type=Path, default=ROOT / "compliance-report.json")
    ap.add_argument("-o", "--output", type=Path, default=ROOT / "compliance-report.pdf")
    args = ap.parse_args()

    try:
        from fpdf import FPDF
    except ImportError:
        print("[ERR] fpdf2 gerekli: pip install fpdf2", file=sys.stderr)
        return 1

    if not args.input.is_file():
        print(f"[ERR] {args.input} yok — once: python3 scripts/compliance_build.py", file=sys.stderr)
        return 1

    data = json.loads(args.input.read_text(encoding="utf-8"))
    es = data.get("executiveSummary") or {}
    controls = data.get("securityControls") or []

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Linux Log Guardian - Compliance Report", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Generated: {data.get('reportDate', '')[:19]}", ln=True)
    pdf.cell(0, 6, f"Standards: {', '.join(data.get('standards', []))}", ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for label, key in [
        ("Pass rate", "passRatePct"),
        ("Controls", "controlsPassed"),
        ("Events", "totalEventsProcessed"),
        ("Alerts", "totalAlerts"),
        ("FP rate %", "fpRatePct"),
    ]:
        val = es.get(key, "—")
        if key == "controlsPassed":
            val = f"{es.get('controlsPassed', 0)}/{es.get('controlsTotal', 0)}"
        pdf.cell(0, 5, f"  {label}: {val}", ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Security Controls", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    w = pdf.epw
    for c in controls:
        line = pdf_safe(f"[{c.get('standard')}] {c.get('id')} {c.get('status')} - {c.get('name')}")
        pdf.multi_cell(w, 5, line)
        ev = pdf_safe((c.get("evidence") or "")[:200])
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(w, 4, pdf_safe(f"  Evidence: {ev}"))
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(
        pdf.epw,
        4,
        pdf_safe(
            "CONFIDENTIAL - Auto-generated by Log Guardian. For audit and KVKK/PCI/SOC2 evidence packs.",
        ),
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(args.output))
    print(f"[compliance_pdf] -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
