#!/usr/bin/env python3
"""OWASP CRS ozet imzalarini rules/crs-bundle.rules dosyasina yazar (ag gerektirmez)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "rules" / "crs-bundle.rules"

# 80+ PCRE2 satiri — import_crs.py ciktisi ile uyumlu
PATTERNS = [
    r"(?i)(?:union\s+(?:all\s+)?select|select\s+.+\s+from)",
    r"(?i)(?:insert\s+into|delete\s+from|drop\s+(?:table|database))",
    r"(?i)(?:update\s+\w+\s+set|exec\s*\(|execute\s*\()",
    r"(?i)(?:xp_cmdshell|sp_executesql|waitfor\s+delay|benchmark\s*\()",
    r"(?i)(?:0x[0-9a-f]{8,}|char\s*\(\s*\d)",
    r"(?i)<script[\s>\\/]",
    r"(?i)javascript\s*:",
    r"(?i)on(?:load|error|click|mouse|focus)\s*=",
    r"(?i)(?:document\.cookie|document\.write|\.innerHTML\s*=)",
    r"(?i)(?:\.\./|\.\.\\|%2e%2e%2f|%252e%252e)",
    r"(?i)(?:/etc/passwd|/etc/shadow|/proc/self/)",
    r"(?i)(?:file://|php://filter|php://input|data://)",
    r"(?i)(?:\$\(|`[^`]+`|\|\s*(?:sh|bash|zsh)\b)",
    r"(?i)(?:;[\s]*(?:wget|curl|nc|bash|sh)\s)",
    r"(?i)(?:cmd\.exe|powershell\s+-)",
    r"(?i)(?:169\.254\.169\.254|metadata\.google)",
    r"(?i)(?:localhost|127\.0\.0\.1|0\.0\.0\.0|::1)",
    r"(?i)(?:gopher://|dict://)",
    r"(?i)(?:sqlmap|nikto|nmap|masscan|acunetix|nessus|dirbuster|gobuster|wfuzz|hydra)",
    r"(?i)(?:\|\||&&)\s*(?:cat|ls|id|whoami|uname)",
    r"(?i)\|\s*whoami\b",
    r"(?i)/(?:bin/sh|bin/bash)\b",
    r"(?i)(?:base64_decode|eval\s*\(|assert\s*\()",
    r"(?i)(?:GLOBALS|_REQUEST|_POST|_GET)\[",
    r"(?i)(?:information_schema|mysql\.user)",
    r"(?i)(?:load_file|into\s+outfile|into\s+dumpfile)",
    r"(?i)(?:concat\s*\(|group_concat)",
    r"(?i)(?:sleep\s*\(|pg_sleep|benchmark\s*\()",
    r"(?i)(?:<iframe|<object|<embed)",
    r"(?i)(?:alert\s*\(|prompt\s*\(|confirm\s*\()",
    r"(?i)(?:vbscript:|livescript:)",
    r"(?i)(?:\.cookie\b|\.execScript)",
    r"(?i)(?:/win\.ini|/boot\.ini)",
    r"(?i)(?:%00|%0a|%0d)",
    r"(?i)(?:\x00|\\x00)",
    r"(?i)(?:etc/passwd%00)",
    r"(?i)(?:\.\.%2f|\.\.%5c)",
    r"(?i)(?:WEB-INF|META-INF)",
    r"(?i)(?:\.git/|\.svn/|\.env)",
    r"(?i)(?:aws\.amazonaws\.com|169\.254\.)",
    r"(?i)(?:internal|intranet|corp\.)",
    r"(?i)(?:socket\.|fsockopen|pfsockopen)",
    r"(?i)(?:system\s*\(|passthru|shell_exec|popen)",
    r"(?i)(?:proc_open|pcntl_exec)",
    r"(?i)(?:include\s*\(|require\s*\()",
    r"(?i)(?:auto_prepend|allow_url_include)",
    r"(?i)(?:mosconfig|joomla)",
    r"(?i)(?:wp-config|wordpress)",
    r"(?i)(?:\$\{jndi:|\$\{lower:)",
    r"(?i)(?:log4j|jndi\.ldap)",
    r"(?i)(?:__proto__|constructor\.prototype)",
    r"(?i)(?:application/json.*\.\./)",
    r"(?i)(?:\badmin\b.*\bpassword\b)",
    r"(?i)(?:\bor\b\s*['\"]?\d+['\"]?\s*=\s*['\"]?\d+)",
    r"(?i)(?:';\s*--|\";\s*--)",
    r"(?i)(?:/\*!\d{5})",
    r"(?i)(?:hex\s*\(|unhex\s*\()",
    r"(?i)(?:convert\s*\(|cast\s*\()",
    r"(?i)(?:@@version|version\s*\()",
    r"(?i)(?:sys\.databases|master\.\.)",
    r"(?i)(?:xp_dirtree|xp_fileexist)",
    r"(?i)(?:sp_oacreate|sp_addextendedproc)",
    r"(?i)(?:UTL_HTTP|DBMS_LDAP)",
    r"(?i)(?:CHR\s*\(|ASCII\s*\()",
    r"(?i)(?:NVL\s*\(|DECODE\s*\()",
    r"(?i)(?:ROWNUM|DUAL\s+FROM)",
    r"(?i)(?:BENCHMARK\s*\(\d+)",
    r"(?i)(?:SLEEP\s*\(\d+)",
    r"(?i)(?:WAITFOR\s+DELAY)",
    r"(?i)(?:pg_sleep\s*\()",
    r"(?i)(?:copy\s+from\s+program)",
    r"(?i)(?:;\s*shutdown\s*;)",
    r"(?i)(?:;\s*drop\s+)",
    r"(?i)(?:<svg[^>]*onload)",
    r"(?i)(?:<img[^>]+src\s*=\s*['\"]?javascript)",
    r"(?i)(?:expression\s*\()",
    r"(?i)(?:url\s*\(\s*['\"]?javascript)",
    r"(?i)(?:data:text/html)",
    r"(?i)(?:&#x[0-9a-f]+;)",
    r"(?i)(?:\\u003cscript)",
    r"(?i)(?:%3Cscript|%3C%2Fscript)",
    r"(?i)(?:\.htaccess|\.htpasswd)",
    r"(?i)(?:cgi-bin/)",
    r"(?i)(?:phpmyadmin|pma_)",
    r"(?i)(?:\.aws/credentials)",
    r"(?i)(?:kubeconfig|\.kube/)",
    r"(?i)(?:id_rsa|authorized_keys)",
    r"(?i)(?:\.\./\.\./\.\./)",
    r"(?i)(?:%c0%ae%c0%ae)",
    r"(?i)(?:TRACE\s+METHOD|TRACK\s+METHOD)",
    r"(?i)(?:OPTIONS\s+.+\.\./)",
    r"(?i)(?:multipart/form-data.*\.\./)",
    r"(?i)(?:Content-Type:\s*application/xml)",
    r"(?i)(?:<!ENTITY\s+\w+\s+SYSTEM)",
    r"(?i)(?:<!DOCTYPE[^>]+ENTITY)",
    r"(?i)(?:\]\]>\s*<)",
    r"(?i)(?:\$\{.*\})",
    r"(?i)(?:\{\{.*\}\})",
    r"(?i)(?:\$\(.*\))",
    r"(?i)(?:runtime\.exec)",
    r"(?i)(?:ProcessBuilder)",
    r"(?i)(?:java\.lang\.Runtime)",
    r"(?i)(?:os\.system|subprocess)",
    r"(?i)(?:pickle\.loads|yaml\.load)",
    r"(?i)(?:__import__\s*\()",
    r"(?i)(?:compile\s*\()",
    r"(?i)(?:exec\s*\(|eval\s*\()",
    r"(?i)(?:\.\./etc/hosts)",
    r"(?i)(?:/var/www/.*\.php\.)",
    r"(?i)(?:\.bak|\.old|\.swp)",
    r"(?i)(?:backup\.sql|dump\.sql)",
    r"(?i)(?:\.DS_Store)",
    r"(?i)(?:crossdomain\.xml)",
    r"(?i)(?:clientaccesspolicy\.xml)",
    r"(?i)(?:server-status|server-info)",
    r"(?i)(?:actuator/health|actuator/env)",
    r"(?i)(?:swagger\.json|openapi\.json)",
    r"(?i)(?:\.well-known/)",
    r"(?i)(?:debug=true|trace=true)",
    r"(?i)(?:phpinfo\s*\()",
    r"(?i)(?:show\s+tables|show\s+databases)",
]

def main() -> int:
    lines = [
        "# Uretildi: scripts/generate_crs_bundle.py — OWASP CRS ozet (80+ imza)",
        "# rules.conf: CRS_RULES=rules/crs-bundle.rules",
        "",
    ]
    for p in PATTERNS:
        lines.append(f"CRS_REGEX={p}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK {len(PATTERNS)} patterns -> {OUT}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
