#!/usr/bin/env python3
"""Award / showcase ZIP — deploy gate sonrasi (Awwwards, FWA, portfolio)."""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "assets/website"
DEPLOY = ROOT / "assets/website-deploy"
OUT_DIR = ROOT / "dist/website-award-pack"
ZIP_PATH = ROOT / "dist/linux-log-guardian-website-award.zip"
REPORT_PATH = ROOT / "website-award-pack-report.json"

SCREENSHOTS = (
    "screenshots/dashboard-fleet.png",
    "screenshots/dashboard-tests.png",
)
EVIDENCE_COPY = (
    "evidence/soak-report.json",
    "evidence/competitive-proof.json",
)


def git_sha() -> str:
    try:
        return (
            subprocess.check_output(
                ["git", "rev-parse", "--short", "HEAD"],
                cwd=ROOT,
                stderr=subprocess.DEVNULL,
                text=True,
            )
            .strip()
        )
    except (subprocess.CalledProcessError, OSError):
        return ""


def count_embedded_tests(site: Path) -> int:
    tr = site / "test-results.js"
    if not tr.is_file():
        return 0
    text = tr.read_text(encoding="utf-8", errors="replace")
    return len(re.findall(r'"id"\s*:\s*"[^"]+"', text))


def count_locales() -> int:
    loc = ROOT / "assets/website/locales"
    if not loc.is_dir():
        return 0
    return len(list(loc.glob("*.json")))


def read_meta(path: Path, name: str) -> str:
    if not path.is_file():
        return ""
    m = re.search(
        rf'<meta\s+name="{re.escape(name)}"\s+content="([^"]*)"',
        path.read_text(encoding="utf-8", errors="replace"),
    )
    return m.group(1) if m else ""


def deploy_file_count() -> int:
    if not DEPLOY.is_dir():
        return 0
    return sum(1 for p in DEPLOY.rglob("*") if p.is_file())


def write_submission_md(path: Path, manifest: dict) -> None:
    langs = manifest.get("languages", 9)
    tests = manifest.get("tests_embedded", 74)
    soak = manifest.get("soak", {})
    path.write_text(
        f"""# Linux Log Guardian — Web Experience Submission

**Product:** Open-source nginx WAF (Turkey) · log → OWASP CRS → kernel ban  
**Site type:** Static marketing + evidence (not the live dashboard)  
**Built:** {manifest.get("build_date", "")} · git `{manifest.get("git_sha", "—")}`

## Live preview (local)

```bash
bash scripts/website_deploy_gate.sh
LG_WEBSITE_PREVIEW=deploy bash scripts/preview_website.sh
```

## Design intent

Immersive scroll narrative inspired by studio-grade sites ([Active Theory](https://activetheory.net/) tier **feel**), adapted for a **product** site:

- Enter curtain · chapter index · spine/WebGL (desktop) · scroll-synced reveals
- Strict CSP + SRI + Trusted Types — no `unsafe-inline`
- 9 languages · reduced-motion + mobile `lg-motion-lite` (WebGL off)
- Real Playwright dashboard screenshots (fleet + `/tests`)

## Technical proof

| Metric | Value |
|--------|-------|
| Embedded automated tests | {tests} |
| i18n locales | {langs} |
| 72h soak | {soak.get("duration_hours", 72)}h · {soak.get("samples", 864)} samples · {soak.get("failures", 0)} fail |
| Deploy package files | {manifest.get("deploy_files", "—")} |
| CSP | hash-only scripts · `require-sri-for` |

## Credits

Linux Log Guardian — MIT · [GitHub](https://github.com/kurtulusutkucenik/Linux-Log-Guardian)

## TR özet

Statik tanıtım sitesi: kurulum rehberi, rakip karşılaştırma, kanıt PDF/JSON. Dashboard bu sitede **çalışmaz** — kurulum sonrası `:8443` kullanıcı sunucusunda.

---
Generated by `bash scripts/website_award_pack.sh`
""",
        encoding="utf-8",
    )


def main() -> int:
    if not SITE.is_dir():
        print("[website_award_pack] FAIL: assets/website yok", file=sys.stderr)
        return 1
    if not DEPLOY.is_dir():
        print(
            "[website_award_pack] FAIL: website-deploy yok — once website_deploy_gate",
            file=sys.stderr,
        )
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    missing = []
    for rel in SCREENSHOTS:
        if not (SITE / rel).is_file():
            missing.append(rel)
    if missing:
        print(
            f"[website_award_pack] FAIL: eksik screenshot: {', '.join(missing)}",
            file=sys.stderr,
        )
        print("  FIX: bash scripts/website_dashboard_screenshots.sh --force", file=sys.stderr)
        return 1

    (OUT_DIR / "screenshots").mkdir()
    for rel in SCREENSHOTS:
        shutil.copy2(SITE / rel, OUT_DIR / "screenshots" / Path(rel).name)

    (OUT_DIR / "evidence").mkdir()
    for rel in EVIDENCE_COPY:
        src = SITE / rel
        if src.is_file():
            shutil.copy2(src, OUT_DIR / "evidence" / Path(rel).name)

    soak_summary: dict = {}
    soak_path = SITE / "evidence/soak-report.json"
    if soak_path.is_file():
        soak = json.loads(soak_path.read_text(encoding="utf-8"))
        soak_summary = {
            "duration_hours": soak.get("duration_hours"),
            "samples": soak.get("samples"),
            "failures": soak.get("failures"),
            "pass": soak.get("pass"),
        }

    manifest = {
        "product": "Linux Log Guardian",
        "brand_short": "Log Guardian",
        "site_type": "static_marketing",
        "build_date": datetime.now(timezone.utc).isoformat(),
        "git_sha": git_sha(),
        "languages": count_locales(),
        "tests_embedded": count_embedded_tests(SITE),
        "soak": soak_summary,
        "deploy_files": deploy_file_count(),
        "csp_i18n_sri": read_meta(SITE / "index.html", "lg-integrity-i18n"),
        "csp_css_sri": read_meta(SITE / "index.html", "lg-integrity-css"),
        "motion_features": [
            "enter-curtain",
            "chapter-index",
            "scroll-reveal",
            "webgl-desktop",
            "motion-lite-mobile",
            "prefers-reduced-motion",
            "terminal-typewriter",
            "compare-scroll-sync",
        ],
        "screenshots": [Path(s).name for s in SCREENSHOTS],
        "gates": [
            "scripts/website_build.sh",
            "scripts/website_deploy_gate.sh",
            "scripts/website_security_check.sh",
            "scripts/website_i18n_browser_smoke.sh",
        ],
        "github": "https://github.com/kurtulusutkucenik/Linux-Log-Guardian",
        "core_message": "nginx log → WAF → kernel ban · ~15 min · self-hosted · MIT",
    }

    (OUT_DIR / "award-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    write_submission_md(OUT_DIR / "SUBMISSION.md", manifest)

    for asset in ("logo.png", "hero-circuit.png"):
        src = SITE / asset
        if src.is_file():
            shutil.copy2(src, OUT_DIR / asset)

    ZIP_PATH.parent.mkdir(parents=True, exist_ok=True)
    if ZIP_PATH.is_file():
        ZIP_PATH.unlink()
    with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(OUT_DIR.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(OUT_DIR).as_posix())

    report = {
        "date": manifest["build_date"],
        "pass": True,
        "zip": str(ZIP_PATH.relative_to(ROOT)),
        "dir": str(OUT_DIR.relative_to(ROOT)),
        "files": sum(1 for _ in OUT_DIR.rglob("*") if _.is_file()),
        "zip_bytes": ZIP_PATH.stat().st_size,
        "tests_embedded": manifest["tests_embedded"],
        "script": "scripts/website_award_pack.sh",
    }
    REPORT_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print(f"[OK] website_award_pack -> {OUT_DIR.relative_to(ROOT)}")
    print(f"[OK] zip -> {ZIP_PATH.relative_to(ROOT)} ({report['zip_bytes'] // 1024} KiB)")
    print(f"[OK] report -> {REPORT_PATH.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
